### ISSUE TITLE
CHT Code Health (Q2 2023)

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-roadmap#100]
**Overview**: Increasing the health of CHT as a whole over time, piece by piece.

**Progress with high-level steps:**
- [x] [Online user stuck in loading screen when offline](https://github.com/medic/cht-core/issues/7356)
- [ ] [DHIS2 import reports a conflict](https://github.com/medic/cht-core/issues/7447)
- [x] [7163 make cht script available in purge](https://github.com/medic/cht-core/pull/7233#issuecomment-1465667407)

**Comment by andrablaj** [comment]
Closing as marked as `Done`
