### ISSUE TITLE
Improve Accessibility through WC3 Design Patterns

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-roadmap#113]
The [Cognitive Accessibility Guidance](https://www.w3.org/WAI/WCAG2/supplemental/#cognitiveaccessibilityguidance) provides a set of “Objectives” for reducing barriers experienced by people with cognitive and learning disabilities. The Objectives provide an overview and include a set of “Design Patterns”. Each Design Pattern explains what to do in order to improve accessibility, how this helps when applied, and includes examples.

Below are the initial objectives and design patterns to be addressed

Objectives|Design Patterns|CHT Implementation
---|---|---
[Help Users Find What They Need](https://www.w3.org/WAI/WCAG2/supplemental/objectives/o2-find/)|[Make it easy to find the most important actions and information on the page](https://www.w3.org/WAI/WCAG2/supplemental/patterns/o2p04-page-important/) | Floating Action Button https://github.com/medic/cht-core/issues/7998 
[Help Users Understand What Things are and How to Use Them](https://www.w3.org/WAI/WCAG2/supplemental/objectives/o1-understandable/)|[Use a Familiar Hierarchy and Design](https://www.w3.org/WAI/WCAG2/supplemental/patterns/o1p02-familiar-design/)|NAV
[Help Users Avoid Mistakes and Know How to Correct Them](https://www.w3.org/WAI/WCAG2/supplemental/objectives/o4-minimize-mistakes/)|[Make it Easy to Undo Form Errors](https://www.w3.org/WAI/WCAG2/supplemental/patterns/o4p05-form-undo/)|TBD

## 2023 Q3
- [ ] [Make it Easy to Undo Form Errors](https://www.w3.org/WAI/WCAG2/supplemental/patterns/o4p05-form-undo/)

## Next
- [ ] [Navigation](https://www.figma.com/file/3wFzMcNEGxV6se1QWftckk/UX-Stages?type=design&node-id=2270-23119&mode=design&t=me3u4FYyJo9YKBP4-0)

## Done

- [x] [Floating Action Button](https://github.com/medic/cht-core/issues/7998)

**Comment by andrablaj** [comment]
Closing as marked as `Done`
