### ISSUE TITLE
cht-sync and cht-pipeline

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-roadmap#115]
**Description**: Ecosystem will work on cht-sync and cht-pipeline open issues from Q4 2022. The goal is to synchronize data from CouchDB to PostgreSQL, facilitating analytics on a Superset dashboard in real-time.

**Objectives**
- [x] Close out tickets from Q4 2022
- [x] Testing
- [ ] Deploy with real world users

**Comment by andrablaj** [comment]
@Phil-Mwago should `Deploy with real world users` checkbox still be part of this ticket or is it covered by #124 ?

**Comment by Phil-Mwago** [comment]
This was a Q2 OKR. It is covered by #124 in Q3 as an OKR since we closed out the teckets.

**Comment by andrablaj** [comment]
Are we waiting on other tickets to consider this ticket done? As right now, it is in the `Now` column on the [roadmap](https://github.com/orgs/medic/projects/112/views/16).

**Comment by Phil-Mwago** [comment]
No, moving this to the done. But keeping an eye on this [issue](https://github.com/medic/cht-sync/issues/23).

**Comment by andrablaj** [comment]
Closing as marked as `Done`
