### ISSUE TITLE
Cybersecurity (Code Health Focus for Q4)

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-roadmap#117]
### Initiatives

- [x] https://github.com/medic/medic-infrastructure/issues/770
- [x] https://github.com/medic/cht-core/issues/8335
- [x] https://github.com/medic/cht-core/issues/6289
- [ ] https://github.com/medic/cht-core/issues/8316
- [x] Plan for user friendly authentication (eg: one time pass, magic links for all, etc)
- [ ] https://github.com/medic/cht-core/issues/8334
- [ ] https://github.com/medic/cht-core/issues/8182
- [ ] Reports communicated to partners

**Comment by Reagan** [comment]
@garethbowen Could I add the following KR for this objective

1. Security awareness training sessions for partners showcasing CHT deployment security best-practices. Improving security could be a rationale for encouraging partners to upgrade CHT versions.
2.

**Comment by garethbowen** [comment]
@Reagan That sounds more like an initiative than a key result?

**Comment by garethbowen** [comment]
Good progress was made in Q4. Closing the roadmap issue and we can raise a new one in the future for the next round of items.
