### ISSUE TITLE
Q4 2023 Form errors are easy to debug

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-roadmap#120]
**Key Result**: 7 app developers report that efforts from this OKR have improved their form development workflow.

--- 

**Early August 2023 update:** - this will mostly be focused on Enketo uplift
**Late Sept 2023 update:** - Enketo uplift not quite done, continuing into Q4

In Allies [synthesis of the nuggets](https://miro.com/app/board/uXjVP6LWtDg=/), two items problem statements out:
* "There is not enough guidance or active feedback when building forms"
* "Coding with XLSX is a bad experience"

When you couple this with [our OGSMs](https://docs.google.com/document/d/1avvwymMKSFoPnJJtO2y47k7Ojzy3oq1NtPW_BALQbbg/edit) that have an entry of "config. defect tickets for MoH X, Y and Z", it makes sense we should focus on this.

The goal should be to reduce the total time it takes to build a form by assessing the largest pain points for app developers and making them less painful.  This might include, but is not limited to:

* offering a library of sample forms - both extending what forms are in [default config](https://github.com/medic/cht-core/tree/master/config/default) and adding public documentation on how to use it
* search for common errors reported from app serv/forums, extend CHT Conf to prevent and give explicit fixes for
* offer the ability to chain together smaller forms.  Smaller should mean  that are easier to comprehend and maintain 
* more!

**_Think beyond CHT Conf!!_** Many smaller wins in other, related areas can result in less errors or easier to debug errors!

**Comment by garethbowen** [comment]
One related thought I've been mulling over is extending the Test Harness with a no-code version (JSON `given` and `then`). Writing tests should be part of writing forms, so making this easier lowers the overall burden and speaks to "debug" in the issue title. One idea might be to run an actual CHT instance like a full e2e suite which would mean it could be extended later to test other things like interop and dashboards too.

**Comment by mrjones-plip** [comment]
Citing these  as important for the Enketo uplift effort:

* [Make code for Enketo forms reusable outside cht-core](https://github.com/medic/cht-core/issues/7462) - required for supporting new Enekto code in cht-conf-test-harness
* [Add additional tests for Enketo Form functionality](https://github.com/medic/cht-core/issues/7600) - Needed to reduce the manual testing load that would come from an Enekto upgrade
