### ISSUE TITLE
The CHT is interoperating with other systems in production

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-roadmap#123]
**Key results**
* [ ] Support 1 active deployment in production.
- [ ] Enhance the reference application by adding the OpenMRS mediator.
- [ ] Publish documentation on building mediators.
- [ ] Advocacy: 
- - [ ] Document learnings/enhancements on readme and doc site
- - [x] Publish a blog post
- - [ ] Publish a white paper

**Original key Result: Q3 & Q4 2023**:
- [x] Complete the referral workflow: happy path in addition to the LTFU. The CHW can refer the patient to a health facility, once the patient is attended to at the health facility, this action updates on the CHT.
- [x] Have 2 active production environments.

**Details/Tasks**:

**Comment by andrablaj** [comment]
[Doc](https://docs.google.com/document/d/12FaLc8ToOWqhrSdRuFkzVYpiCxokCzmuKco8yNrJvlY/edit#heading=h.feld6ba8s0qd)

**Comment by Phil-Mwago** [comment]
To include a revamp of the CHT Interoperability course later in 2024

**Comment by Phil-Mwago** [comment]
Closing this as it is covered in #167
