### ISSUE TITLE
Key insights for the improvement of the CHT have been obtained through user research

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-roadmap#125]
**Key Result**: 
1. 6 interviews with users: app developers (2 per month).
2. UX repository populated with new insights for Ecosystem

**Details/Tasks**
Gather feedback from users and achieve a specified satisfaction rating regarding the usability and effectiveness of the following:
- [ ] CHT-Interoperability
- [ ] CHT-Sync & CHT-Pipeline

**Comment by andrablaj** [comment]
Closing as marked as `Done`
