### ISSUE TITLE
Partners can learn and adopt the CHT-Interoperability feature through the CHT-Academy

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-roadmap#126]
**Key Result**: 
1. Learning materials have been published for the 5 modules
1. The complete CHT-Interoperability is accessible on the CHT-Academy
1. Programs teammates have been made aware of the new resources
1. The community has been made aware of the new resources via the forum and CHT Roundup

**Details/Tasks**
- [x] Create modules topics
- [x] Draft the following training materials for each module
- - Training decks
- - Training videos
- - Compile the training resources for dissemination.
- [ ] Evangelism of the course internally and through EA:
- - Draft a blog post
- - Post on the CHT forum
- - Medics socials and the community team

**Comment by andrablaj** [comment]
Closing as marked as `Done`
