### ISSUE TITLE
Unauthorized users cannot access CHT apps

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-roadmap#129]
## 2023 Q4

- [x] Research CHW perception and understanding around app security with a goal to prevent unauthorized access to CHW's apps (See [#7284](https://github.com/medic/cht-core/issues/7284), [#3237](https://github.com/medic/cht-core/issues/3237), and [learning agenda](https://docs.google.com/document/d/1pOyCWbh6Zb6K_uXBh48DBiQx6QyvovtF3rz7lsDKWhk/edit#heading=h.8h6u3f2adv5m))

**Comment by andrablaj** [comment]
Closing as marked as `Done`
