### ISSUE TITLE
Users leverage CHT Sync & CHT Pipeline learnings & documentation for seamless deployment in new and ongoing projects

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-roadmap#136]
**Current Key Result**

- [x] A migration path from couch2pg to CHT Sync has been documented
- [x] Define and build core models

**Key Result:** 
1. Reusable default dashboards are published
1. Two (2) reusable default  schemas are published
1. A migration path from couch2pg to CHT Sync has been documented

**Comment by andrablaj** [comment]
Closing as marked as `Done`
