### ISSUE TITLE
Transitioning project deployment information to salesforce for easier and more accurate tracking

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-roadmap#43]
**Brief overview of the initiative**
Project deployment information is currently managed in various places (docs, db's, etc). For transparency, accuracy, and analytics purposes, we want to transition all information to salesforce. The below doc has been started to pull in related info and is formatted for bulk upload to salesforce. We may also want to explore if/how data can be pulled directly from db's to auto update
salesforce

**Link to the google doc where info for the initiative is being managed**
https://docs.google.com/spreadsheets/d/1yT0Ee73ZrMQ3kDVQqFLgPSWjCOJ-fxiQ8lY-iNRo4Tw/edit?ts=5dcb141b#gid=0

**Comment by kennsippell** [comment]
Tagging @alixemden since she is learning SalesForce Apex and has some deep thoughts on this.

**Comment by MaxDiz** [comment]
replaced with https://github.com/medic/cht-core/issues/6672 for scheduling in a release
