### ISSUE TITLE
Improve System Status Visibility while updating / upgrading the app

### ISSUE THREAD

**Issue by n-orlowski** [medic/cht-roadmap#44]
**Brief overview of the initiative**
Several issues in the End User Backlog are related to the lack of visibility of the system status. For example, users are shutting down the app assuming it is broken while it is loading; CHWs are refreshing the app unknowing that it is still loading, etc. 

**Link to the google drive folder where info for the initiative is being managed**
https://docs.google.com/document/d/1VDjuLt_hLfy_v9iml8Ny4LCtOiJqIhcRQhLYg20b4v0/edit#heading=h.q31g948sivit

- https://github.com/medic/cht-core/issues/4480
- https://github.com/medic/cht-core/issues/5618
- https://github.com/medic/cht-core/issues/5207
- https://github.com/medic/cht-core/issues/6521
- https://github.com/medic/cht-core/issues/5874
- https://github.com/medic/cht-core/issues/6391
- https://github.com/medic/medic-android/issues/49
- https://github.com/medic/cht-core/issues/6292

**Comment by MaxDiz** [comment]
Not part of current 2021 priorities so closing. Reopen if re-prioritized
