### ISSUE TITLE
Facilitating Household  to Provider Messaging Interaction 

### ISSUE THREAD

**Issue by joyannee** [medic/cht-roadmap#45]
**Brief overview of the initiative**

Interaction and integration of provider facing and client facing tools has not been fully explored. Traditionally patients communicate with the providers via texts and or calls which may pose an economic burden on the household. Tracking of these types of communication are often outside of the CHT making it difficult to track and facilitate client initiated house visits. Communication between CHWs and patients is important to ensure early intervention and avert negative health outcomes that would pose an economic burden on the household. Qualitatively, we know that patients often request visits from their CHWs, either by calling the CHW if they have airtime, or by sending someone to the CHW’s home. However, to date the CHT software only supports CHW-initiated house visits; it does not effectively track or facilitate client initiation of house visits.

**Link to the google drive folder where info for the initiative is being managed**

https://drive.google.com/drive/u/1/folders/1KEFtU_2-8CtKRbbXdQf7HskU8Eb8Eq5h

**Comment by MaxDiz** [comment]
Not part of current 2021 priorities so closing. Reopen if re-prioritized
