### ISSUE TITLE
Improving in-app messenger user experience to streamline patient-provider communication and reduce missed care follow-ups

### ISSUE THREAD

**Issue by joyannee** [medic/cht-roadmap#46]
**Brief overview of the initiative**
The messaging in the CHT has not been updated in the last couple of years. There is a lot of room for improvement to improve the user experience for users. Users would like to perform certain actions based on the information in received messages. In the current infrastructure, users who use the messaging tab often such as those in the VMMC project have to switch between the messaging tab, people tabs and task tabs to be able to complete the workflow.

**Link to the google drive folder where info for the initiative is being managed**
https://drive.google.com/drive/u/1/folders/1zn5kJ6cNakqB8VQ0mcHkMfgCGw0sFseN

**Comment by MaxDiz** [comment]
Not part of current 2021 priorities so closing. Reopen if re-prioritized
