### ISSUE TITLE
Server-side reliability under load

### ISSUE THREAD

**Issue by craig-landry** [medic/cht-roadmap#63]
**Overview**
CHT apps currently suffer from performance issues when operating with thousands of users. CHT apps should be able to scale to thousands of users and remain responsive.

Work on this initiative will come together as CHT 4.0 and involve a server-side architecture shift to architecture v3.

The tasks for this effort can be seen on the [Arch v3 board](https://github.com/orgs/medic/projects/103/views/1).

**Comment by garethbowen** [comment]
Released in 4.0.0
