### ISSUE TITLE
Easy confident CHT upgrades for apps

### ISSUE THREAD

**Issue by craig-landry** [medic/cht-roadmap#66]
**Overview**
CHT apps sometimes fall out-of-date and miss out on new features, technical improvements, and other enhancements. Upgrading the CHT should be easy to do in a manner that brings confidence to project members.

- [ ] Updated opportunity solution tree
- [ ] Solution story maps
- [ ] Solution selection
- [ ] Assumption investigation
- [ ] Development
- [ ] Deployment

**Comment by Reagan** [comment]
Duplicate of [this](https://github.com/medic/cht-roadmap/issues/92 ) cc @craig-landry
