### ISSUE TITLE
Launch self-guided learning platform for building CHT apps

### ISSUE THREAD

**Issue by smbuthia** [medic/cht-roadmap#73]
Medic as a steward of the CHT has made available resources that make it easier to design, build, and deploy CHT applications. These include design resources, guides, tutorials, and reference applications. As part of our ongoing efforts to strengthen the resources available to the CHT community, we are working on the launch of an online learning platform that will enhance the CHT onboarding experience through the delivery of multimedia learning content including video guides and tutorials.

The launch of the online platform will be in the following phases:
1. Selection of a free and open-source learning management system that will deliver a quality learning experience to the CHT community - Done
2. Designing the learning curriculum, including the modules, and delivery sequence - Done
3. Development of presentation decks and supporting documentation - In progress
4. Development of video guides and tutorials that will augment existing resources in the CHT docs site - In progress
5. Integrating course content on the LMS - Not started
6. Reviewing and publishing course content - Not started

**Comment by andrablaj** [comment]
Closing as marked as `Done`
