### ISSUE TITLE
Data-Driven Tasks: Encourage use of Performance Management and Supervisor Workflows

### ISSUE THREAD

**Issue by abbyad** [medic/cht-roadmap#78]
Tasks were added to the CHT in 2015 in support of LG’s first SmartHealth app. Given recent studies validating that improved supervisor task workflows will positively impact supervisor and CHW metrics, resulting in more timely, equitable care for communities, we should encourage the use of data-driven tasks in CHT apps. This can be done by more proactively packaging and sharing data-driven task workflows and resources with the broader CHT community so that they can be included in new and existing deployments. This is also a good opportunity to discover how Tasks can be improved further.

We should explore how app developers in the CHT community can best include data-driven tasks and patient workflows in their apps. The result may be guides, tutorials, and a reference app that showcases performance management with some of the following workflows:
- **Missed high-risk tasks** being elevated to supervisors
- **Inactivity tasks for supervisors** to follow up with CHWs that have either been inactive, or have been unable to sync within a set timeframe
- **Elevation of missed targets** as tasks for supervisors for follow up
- **CHW Performance Warning** to identify CHWs who may need to be replaced or more actively supported
- **Manager dashboards** showing task completion

The reference app can also showcase the following key task features:

- Tasks are ranked/labeled/ordered by priority
- Tasks have due time/date (and an expiry time)
- Supervisors have automatic tasks to follow up urgent CHW tasks that were not completed 
- Enable assignment of task to ‘in person’ or ‘Call/remote,’ allowing supervisors to improve overall performance by staying in closer contact with more CHWs more regularly than doing in person visits only
- Enable creation of notifications and SMS messages to supervisors’ smart device when a priority task is assigned.
- Enable supervisors to add notes regarding the outcome of the task

In order for partners to collaborate more easily on building task workflows, we could explore easy-to-use interfaces to enable tech partners to design and test these tasks as well.

**Comment by andrablaj** [comment]
Closing as marked as `Done`
