### ISSUE TITLE
Review haproxy as auditing solution

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-roadmap#95]
- [ ] https://github.com/medic/cht-core/issues/8182

**Comment by derickl** [comment]
Are there other potential alternatives that would be appropriate?

**Comment by garethbowen** [comment]
@derickl One option is using nginx for both front and back end, but there are plenty of others we can look into.

**Comment by garethbowen** [comment]
I've added this to the [cybersecurity roadmap item](https://github.com/medic/cht-roadmap/issues/117) as an initiative rather than an objective...
