### ISSUE TITLE
Finalize on Interoperability

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-roadmap#97]
- [x] Instance of OpenHIM with configuration put online so all CHISs can integrate against it
- [x] April 14 - Beta flows for each CHISs working with sync between their own events
- [x] April 21 - Beta flow for CHISs working with sync between any other CHIS events
- [x] April 21 - All findings published in GitHub (and OpenHIE wiki as needed)

**Comment by andrablaj** [comment]
Closing as marked as `Done`
