### ISSUE TITLE
Actively engaged with ecosystem on interoperability needs

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-roadmap#99]
There is some genuine interest in the work we are doing. 

- [ ] Criteria to assess impact and our level of engagement.

Interop discussions happening with 3 partners:
- MoH Kenya: eCHIS-AfyaKE integration
- MoH Uganda: eCHIS-WASH integration
- I-TECH Malawi project

**Comment by andrablaj** [comment]
Closing as marked as `Done`
